name: tiktoklikescroller
description: A vertical fullscreen scroll implementation that snaps in place, similar to the TikTok app
version: 0.2.3
homepage: https://github.com/dmt195
repository: https://github.com/dmt195/tiktok-flutter-plugin

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
