#The name of your workflow.
name: Test
# Trigger the workflow on push or pull request
on: [pull_request, push]
#A workflow run is made up of one or more jobs. Jobs run in parallel by default.
jobs:
  test:
    #The type of machine to run the job on. [windows,macos, ubuntu , self-hosted]
    runs-on: ubuntu-latest
    #sequence of tasks called
    steps:
      # The branch or tag ref that triggered the workflow will be checked out.
      # https://github.com/actions/checkout
      - uses: actions/checkout@v1
      # Setup a flutter environment.
      # https://github.com/marketplace/actions/flutter-action
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.0.0"
          channel: "beta"
      - run: flutter pub get
      # run static analyse code
      - run: flutter analyze
        working-directory: example
      # run  flutter widgets tests  and unit tests
      - run: flutter test --coverage
        working-directory: example
      # Upload coverage reports to Codecov
      # https://github.com/marketplace/actions/codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info
